#!/usr/bin/env python3
"""Compile content/*.json into one idempotent SQL seed for the dashboard
SQL editor (no Python or service key needed at run time). Stable keys:
courses by slug, videos by (course_id, ord), questions by (video_id, ord),
finals by (course_id, ord). Re-running updates in place and never orphans
progress. Regenerate whenever a content JSON changes:
    python3 tools/make_content_sql.py > content/SEED-CONTENT.sql
"""
import json, glob, sys

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

ORDER = ["fundamentals", "reentry", "anger", "coparenting", "manhood"]
PUBLISH = ["fundamentals", "reentry", "anger", "coparenting"]

def session_rows(d):
    """Accept either videos[] (legacy importer shape) or sessions[] (Seven Secrets)."""
    rows = d.get("videos") or d.get("sessions") or []
    out = []
    for v in rows:
        ref = v.get("vimeo")
        if ref is None or ref == "":
            ref = v.get("video_url")
        if ref is None or ref == "" or ref is False:
            ref = "pending"
        out.append({
            "ord": v["ord"],
            "title": v["title"],
            "duration_seconds": int(v.get("duration_seconds") or 0),
            "vimeo": str(ref),
            "checkpoint": v.get("checkpoint") or [],
            "poster": v.get("poster") or "",
        })
    return out

def course_hours(d, rows):
    if d.get("hours") is not None:
        try:
            return float(d["hours"])
        except (TypeError, ValueError):
            pass
    dur = sum(r["duration_seconds"] for r in rows)
    if dur > 0:
        return round(dur / 3600.0, 1)
    return 0.0

def main():
    docs = {}
    for p in sorted(glob.glob("content/*.json")):
        if p.endswith("example.json") or p.endswith("short-course-pages.json"):
            continue
        d = json.load(open(p))
        if "slug" not in d:
            continue
        docs[d["slug"]] = d
    out = []
    out.append("-- Generated by tools/make_content_sql.py from content/*.json.")
    out.append("-- Paste whole into the Supabase SQL editor and Run once. Idempotent:")
    out.append("-- re-running updates rows in place by stable keys and orphans nothing.")
    out.append("begin;")
    out.append("")
    out.append("-- Schema alignment, idempotent: the base schema predates these.")
    out.append("alter table certificate_courses add column if not exists published boolean not null default true;")
    out.append("alter table certificate_courses alter column hours set default 0;")
    out.append("create unique index if not exists course_videos_course_ord_key on course_videos (course_id, ord);")
    out.append("create unique index if not exists quiz_questions_video_ord_key on quiz_questions (video_id, ord);")
    out.append("create unique index if not exists final_qa_questions_course_ord_key on final_qa_questions (course_id, ord);")
    for slug in ORDER:
        d = docs.get(slug)
        if not d:
            continue
        rows = session_rows(d)
        hours = course_hours(d, rows)
        out.append(f"\n-- ===== {d['title']} ({slug}) =====")
        out.append("do $$")
        out.append("declare cid uuid; vid uuid;")
        out.append("begin")
        out.append(f"  select id into cid from certificate_courses where slug = {q(slug)};")
        out.append("  if cid is null then")
        out.append(f"    insert into certificate_courses (slug, title, hours, published) values ({q(slug)}, {q(d['title'])}, {hours}, false) returning id into cid;")
        out.append("  else")
        out.append(f"    update certificate_courses set title = {q(d['title'])}, hours = {hours} where id = cid;")
        out.append("  end if;")
        for v in rows:
            dur = v["duration_seconds"]
            ref = q(v["vimeo"])
            out.append(f"\n  -- session {v['ord']}: {v['title']}")
            out.append(f"  select id into vid from course_videos where course_id = cid and ord = {v['ord']};")
            out.append("  if vid is null then")
            out.append(f"    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, {v['ord']}, {q(v['title'])}, {ref}, {dur}) returning id into vid;")
            out.append("  else")
            out.append(f"    update course_videos set title = {q(v['title'])}, video_url = {ref}, duration_seconds = {dur} where id = vid;")
            out.append("  end if;")
            for j, cq in enumerate(v["checkpoint"], 1):
                choices = "'" + json.dumps(cq["choices"]).replace("'", "''") + "'::jsonb"
                out.append(f"  if exists (select 1 from quiz_questions where video_id = vid and ord = {j}) then")
                out.append(f"    update quiz_questions set prompt = {q(cq['prompt'])}, choices = {choices}, correct_index = {cq['correct_index']} where video_id = vid and ord = {j};")
                out.append("  else")
                out.append(f"    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, {j}, {q(cq['prompt'])}, {choices}, {cq['correct_index']});")
                out.append("  end if;")
        for j, fq in enumerate(d.get("final_qa") or [], 1):
            out.append(f"  if exists (select 1 from final_qa_questions where course_id = cid and ord = {j}) then")
            out.append(f"    update final_qa_questions set prompt = {q(fq['prompt'])} where course_id = cid and ord = {j};")
            out.append("  else")
            out.append(f"    insert into final_qa_questions (course_id, ord, prompt) values (cid, {j}, {q(fq['prompt'])});")
            out.append("  end if;")
        out.append("end $$;")
    pubs = ", ".join(q(s) for s in PUBLISH)
    out.append("\n-- Open the four live courses to participants; manhood stays dark until its flag flips.")
    out.append(f"update certificate_courses set published = true where slug in ({pubs});")
    out.append(f"update certificate_courses set published = false where slug = {q('manhood')};")
    out.append("commit;")
    print("\n".join(out))

if __name__ == "__main__":
    main()
