#!/usr/bin/env python3
"""Generate assets/js/config.js from env at deploy (AUDIT-V41 WP-L3).
Only the anon key ever appears client-side; that is the entire discipline."""
import os
url = os.environ.get("SUPABASE_URL", "")
anon = os.environ.get("SUPABASE_ANON_KEY", "")
open("assets/js/config.js", "w").write(
    "/* Generated by tools/write_config.py. SUPABASE_ANON_KEY is the public anon\n"
    "   role and is safe to ship; row-level security is the enforcement boundary.\n"
    "   Service-role keys never appear here. */\n"
    f"window.FC_CONFIG = {{ SUPABASE_URL: {url!r}, SUPABASE_ANON_KEY: {anon!r} }};\n")
print("wrote assets/js/config.js")
